export const USER_ACTION_TYPES = {
  SET_CURRENT_USER: "user/SET_CURRENT_USER",
  CHECK_USER_SESSION: "user/CHECK_USER_SESSION",
  GOOGLE_SIGNIN_START: "user/GOOGLE_SIGNIN_START",
  EMAIL_SIGNIN_START: "user/EMAIL_SIGNIN_START",
  SIGN_IN_SUCCESS:"user/SIGN_IN_SUCCESS",
  SIGN_IN_FAILURE:"user/SIGN_IN_FAILURE",
};